import logging
from typing import Optional, Any, List
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from retriever import get_retriever
from config import OPENAI_API_KEY

logger = logging.getLogger(__name__)

QA_TEMPLATE = """You are a senior software engineer analyzing a codebase. Use the retrieved code context to answer the user's question clearly and concisely.
Your response should:
- Explain the code clearly.
- Explicitly reference file names and functions or classes.
- Identify potential bugs or edge cases if applicable.
- Suggest improvements or best practices.
- Provide concise, production-ready technical explanations.

If you don't know the answer, state that clearly instead of guessing.

Context:
{context}"""

# Simple in-memory storage for the chat history
chat_history: List[Any] = []

def get_chat_chain() -> Optional[Any]:
    """
    Initializes a basic LCEL retrieval and QA dictionary state.
    
    Returns:
        Optional[Any]: A dictionary holding the initialized LLM and Retriever, or None if it fails.
    """
    if not OPENAI_API_KEY:
        logger.critical("OPENAI_API_KEY is not set. Cannot initialize chat chain.")
        return None

    try:
        llm = ChatOpenAI(model="gpt-4o-mini", temperature=0, openai_api_key=OPENAI_API_KEY)
        retriever = get_retriever()
        if not retriever:
            logger.error("Retriever could not be initialized.")
            return None
        
        logger.info("Conversational chat chain successfully initialized.")
        return {"llm": llm, "retriever": retriever}
    except Exception as e:
        logger.error("Error initializing chat chain: %s", e)
        return None

def ask_question(query: str, chain: Any = None) -> str:
    """
    Answers a specific question utilizing the initialized LLM and retriever.
    
    Args:
        query (str): The question being asked.
        chain (Any, optional): The dictionary containing 'llm' and 'retriever'. Defaults to None.
        
    Returns:
        str: The answer generated by the LLM.
    """
    global chat_history
    if chain is None:
        chain = get_chat_chain()
        if chain is None:
            return "Error: Could not initialize chat chain."
            
    try:
        llm = chain["llm"]
        retriever = chain["retriever"]
        
        # Retrieve contextual code chunks
        docs = retriever.invoke(query)
        context = "\n\n".join([doc.page_content for doc in docs])
        
        # Initialize messages payload
        messages = [SystemMessage(content=QA_TEMPLATE.format(context=context))]
        messages.extend(chat_history)
        messages.append(HumanMessage(content=query))
        
        # Get AI response
        response = llm.invoke(messages)
        answer = response.content
        
        # Update conversational memory
        chat_history.append(HumanMessage(content=query))
        chat_history.append(AIMessage(content=answer))
        
        # Prune chat history to prevent exceeding context bounds
        if len(chat_history) > 10:
            chat_history = chat_history[-10:]
            
        return answer
    except Exception as e:
        logger.error("Error during question resolution: %s", e)
        return f"Error: {e}"

def chat_loop() -> None:
    """
    Starts the interactive chat loop with conversational memory.
    """
    print("\nStarting chat. Type 'quit' or 'exit' to stop.")
    
    chain = get_chat_chain()
    if not chain:
        print("Failed to load retriever or LLM engine.")
        return

    while True:
        try:
            user_input = input("\nAsk a question about the codebase (or 'quit' to exit): ").strip()
            if not user_input:
                continue
            if user_input.lower() in ['quit', 'exit']:
                break
                
            print("Thinking...")
            answer = ask_question(user_input, chain=chain)
            print(f"\nAnswer:\n{answer}")
        except KeyboardInterrupt:
            print("\nExiting chat loop...")
            break
        except Exception as e:
            logger.error("An unexpected error occurred in the chat loop: %s", e)
            print("An unexpected error occurred. Check the logs for details.")
